/**
 * Generated by `npm run generate:api-types`.
 *
 * Bootstrap placeholder kept in git so modules can import stable type names
 * before a running backend is available. Regenerate after backend OpenAPI
 * changes with ECC_DOCS_ENABLED=1.
 */
export interface paths {
  "/projects": {
    get: { responses: { 200: { content: { "application/json": Project[] } } } };
    post: { requestBody: { content: { "application/json": ProjectCreate } } };
  };
  "/projects/{project_id}/handoff/append": {
    post: { requestBody: { content: { "application/json": HandoffAppend } } };
  };
  "/notebooklm/status": {
    get: { responses: { 200: { content: { "application/json": NotebookLMStatus } } } };
  };
}

export interface Project {
  _id?: string;
  id?: string;
  name?: string;
  client?: string;
  status?: string;
  deadline?: string;
}

export interface ProjectCreate {
  name: string;
  client?: string;
  status?: string;
  deadline?: string;
  budget?: number;
}

export interface HandoffAppend {
  text: string;
  source?: string;
}

export interface NotebookLMStatus {
  local?: Record<string, unknown>;
  notebooklm?: Record<string, unknown>;
}
